export const icons= [
  {
    id:1,
    logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png',
    title:'react'
  },
  {
    id:2,
    logo:'https://icon-library.com/images/react-icon/react-icon-28.jpg',
    title:'redux'
  },
  {
    id:3,
    logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sass_Logo_Color.svg/1280px-Sass_Logo_Color.svg.png',
    title:'scss'
  },
  {
    id:4,
    logo:'http://assets.stickpng.com/images/5847f40ecef1014c0b5e488a.png',
    title:'firebase'
  },
  {
    id:5,
    logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/1024px-HTML5_logo_and_wordmark.svg.png',
    title:'HTML5'
  },
  {
    id:6,
    logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1452px-CSS3_logo_and_wordmark.svg.png',
    title:'CSS3'
  },
  
  {
    id:7,
    logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/600px-JavaScript-logo.png',
    title:'JS'
  }
]